# We will work on a Dogs adoptions dataset here.<br>
the dataset has provided from the link i refered to it in ReadME.

In [2]:
import pandas as pd
import re

In [3]:
df = pd.read_csv('dataset/dogs.csv')

# Configuration setting to show all the elements of tables
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

df.head()

,id,org_id,url,type.x,species,breed_primary,breed_secondary,breed_mixed,breed_unknown,color_primary,color_secondary,color_tertiary,age,sex,size,coat,fixed,house_trained,declawed,special_needs,shots_current,env_children,env_dogs,env_cats,name,status,posted,contact_city,contact_state,contact_zip,contact_country,stateQ,accessed,type.y,description,stay_duration,stay_cost
0,46042150,NV163,https://www.petfinder.com/dog/harley-46042150/...,Dog,Dog,American Staffordshire Terrier,Mixed Breed,True,False,White / Cream,Yellow / Tan / Blond / Fawn,NaN,Senior,Male,Medium,Short,True,True,NaN,False,True,NaN,NaN,NaN,HARLEY,adoptable,2019-09-20T16:37:59+0000,Las Vegas,NV,89147,US,89009,2019-09-20,Dog,Harley is not sure how he wound up at shelter ...,70,124.81
1,46042002,NV163,https://www.petfinder.com/dog/biggie-46042002/...,Dog,Dog,Pit Bull Terrier,Mixed Breed,True,False,Brown / Chocolate,White / Cream,NaN,Adult,Male,Large,Short,True,True,NaN,False,True,NaN,NaN,NaN,BIGGIE,adoptable,2019-09-20T16:24:57+0000,Las Vegas,NV,89147,US,89009,2019-09-20,Dog,6 year old Biggie has lost his home and really...,49,122.07
2,46040898,NV99,https://www.petfinder.com/dog/ziggy-46040898/n...,Dog,Dog,Shepherd,NaN,False,False,Brindle,NaN,NaN,Adult,Male,Large,Short,True,False,NaN,False,True,NaN,NaN,NaN,Ziggy,adoptable,2019-09-20T14:10:11+0000,Mesquite,NV,89027,US,89009,2019-09-20,Dog,Approx 2 years old.\n Did I catch your eye? I ...,87,281.51
3,46039877,NV202,https://www.petfinder.com/dog/gypsy-46039877/n...,Dog,Dog,German Shepherd Dog,NaN,False,False,NaN,NaN,NaN,Baby,Female,Large,NaN,False,False,NaN,False,False,NaN,NaN,NaN,Gypsy,adoptable,2019-09-20T10:08:22+0000,Pahrump,NV,89048,US,89009,2019-09-20,Dog,NaN,62,145.83
4,46039306,NV184,https://www.petfinder.com/dog/theo-46039306/nv...,Dog,Dog,Dachshund,NaN,False,False,NaN,NaN,NaN,Young,Male,Small,Long,True,False,NaN,False,True,True,True,True,Theo,adoptable,2019-09-20T06:48:30+0000,Henderson,NV,89052,US,89009,2019-09-20,Dog,Theo is a friendly dachshund mix who gets alon...,93,241.09

### 1. Extract all dogs with status that is not adoptable

In [4]:
status = 'adoptable'
df_status = df[df['status'] != status]

print(f"Number of not adoptable dogs is {df_status['status'].count()}")
print(df_status[['id','status']].reset_index())

Number of not adoptable dogs is 33
    index        id                    status
0     644  41330726  2018-04-05T05:18:31+0000
1    5549  38169117  2017-05-26T21:43:16+0000
2   10888  45833989  2019-09-01T15:12:06+0000
3   11983  45515547  2019-08-06T12:15:58+0000
4   12495  45294115  2019-07-18T14:20:58+0000
5   12600  45229004  2019-07-11T20:34:42+0000
6   12613  45227052  2019-07-11T14:16:38+0000
7   17619  45569380  2019-08-10T16:00:35+0000
8   18611  44694387  2019-05-14T21:09:27+0000
9   19747  36978896  2016-12-15T13:33:43+0000
10  19845  33218331  2015-09-07T12:57:27+0000
11  22161  42092005  2018-07-05T00:55:08+0000
12  22229  39594038  2017-10-07T23:48:20+0000
13  29283  45895274  2019-09-07T04:09:12+0000
14  30471  45964719  2019-09-13T19:39:28+0000
15  31581  44538917  2019-04-25T01:56:52+0000
16  31888  41430442  2018-04-18T13:45:46+0000
17  33000  45907639  2019-09-08T18:21:21+0000
18  33527  45362806  2019-07-25T19:53:21+0000
19  34188  32590894  2015-06-29T23:58:09+0000
20  35065  31426754  2015-02-07T13:06:43+0000
21  44830  46037827  2019-09-20T01:50:51+0000
22  53168  44044071  2019-02-18T12:02:48+0000
23  53539  27521132  2013-10-10T13:57:39+0000
24  55434  38473806  2017-06-16T18:44:33+0000
25  55467  34101432  2015-12-25T12:28:30+0000
26  55915  45958435  2019-09-13T06:08:17+0000
27  55975  45927580  2019-09-10T16:43:35+0000
28  56013  45916348  2019-09-09T17:05:17+0000
29  56248  45733027  2019-08-24T16:32:31+0000
30  56464  45413997  2019-07-31T16:21:07+0000
31  56473  45406516  2019-07-29T21:50:16+0000
32  56541  45264615  2019-07-15T16:57:05+0000

### 2. For each (primary) breed, determine the number of dogs

In [5]:
breed_primary = df['breed_primary'].value_counts()


breed_primary

Pit Bull Terrier                            7890
Labrador Retriever                          7198
Chihuahua                                   3766
Mixed Breed                                 3242
Terrier                                     2641
Hound                                       2282
German Shepherd Dog                         2122
Boxer                                       2050
Shepherd                                    1972
American Staffordshire Terrier              1862
Beagle                                      1539
American Bulldog                            1134
Australian Cattle Dog / Blue Heeler          973
Dachshund                                    853
Border Collie                                817
Australian Shepherd                          696
Jack Russell Terrier                         637
Husky                                        567
Black Labrador Retriever                     545
Retriever                                    538
Rottweiler                                   533
Catahoula Leopard Dog                        488
Great Pyrenees                               481
Cattle Dog                                   444
Siberian Husky                               439
Shih Tzu                                     421
Staffordshire Bull Terrier                   390
Pointer                                      367
Yorkshire Terrier                            360
Rat Terrier                                  338
Great Dane                                   334
Miniature Pinscher                           317
Greyhound                                    306
Poodle                                       304
Mastiff                                      301
Coonhound                                    286
Doberman Pinscher                            267
Plott Hound                                  265
Treeing Walker Coonhound                     258
Pug                                          255
Pomeranian                                   252
Shar-Pei                                     249
Basset Hound                                 241
Collie                                       236
Cocker Spaniel                               209
Golden Retriever                             203
Black Mouth Cur                              201
Schnauzer                                    200
Maltese                                      183
Akita                                        181
English Bulldog                              177
Bull Terrier                                 176
Mountain Cur                                 168
Chow Chow                                    165
Yellow Labrador Retriever                    158
Chocolate Labrador Retriever                 155
Boston Terrier                               149
Spaniel                                      148
Feist                                        139
Corgi                                        128
Weimaraner                                   126
Anatolian Shepherd                           118
Redbone Coonhound                            104
Saint Bernard                                102
Foxhound                                     100
Belgian Shepherd / Malinois                   94
Bluetick Coonhound                            92
Cairn Terrier                                 91
English Pointer                               90
Black and Tan Coonhound                       88
German Shorthaired Pointer                    88
Whippet                                       83
Cane Corso                                    83
Bichon Frise                                  82
Dalmatian                                     77
Pekingese                                     76
Rhodesian Ridgeback                           74
Alaskan Malamute                              72
Parson Russell Terrier                        70
Italian Greyhound                             66
Dutch Shepherd                                63
Carolina Dog                                  61
Shiba Inu                                     60
Vizsla                                        60
Lhasa Apso                                    60
Wirehaired Terrier                            60
Papillon                                      59
Bullmastiff                                   55
Bloodhound                                    54
Basenji                                       54
Shetland Sheepdog / Sheltie                   54
Standard Poodle                               47
French Bulldog                                46
Jindo                                         46
American Eskimo Dog                           43
Australian Kelpie                             43
Flat-Coated Retriever                         43
Fox Terrier                                   40
Manchester Terrier                            39
English Springer Spaniel                      35
Spitz                                         34
Dogo Argentino                                34
Brittany Spaniel                              31
English Coonhound                             30
Border Terrier                                28
English Setter                                28
Presa Canario                                 27
Toy Fox Terrier                               26
Newfoundland Dog                              26
Miniature Schnauzer                           26
Cardigan Welsh Corgi                          26
Brussels Griffon                              24
Havanese                                      24
Chesapeake Bay Retriever                      23
Cavalier King Charles Spaniel                 23
Dogue de Bordeaux                             22
Schipperke                                    22
Bernese Mountain Dog                          20
English Shepherd                              20
Wheaten Terrier                               19
Saluki                                        19
Airedale Terrier                              19
West Highland White Terrier / Westie          19
Chinese Crested Dog                           18
Irish Terrier                                 17
White German Shepherd                         17
Cockapoo                                      17
Affenpinscher                                 17
Irish Wolfhound                               17
American Foxhound                             17
Canaan Dog                                    17
Mountain Dog                                  16
Patterdale Terrier / Fell Terrier             16
Japanese Chin                                 15
Australian Terrier                            15
Silky Terrier                                 15
Wire Fox Terrier                              15
Standard Schnauzer                            14
Harrier                                       14
Scottish Terrier                              13
Blue Lacy                                     13
Petit Basset Griffon Vendeen                  12
Miniature Poodle                              12
Xoloitzcuintli / Mexican Hairless             11
Pharaoh Hound                                 11
Setter                                        10
German Wirehaired Pointer                     10
Tibetan Mastiff                               10
Neapolitan Mastiff                             9
Tibetan Spaniel                                9
Pembroke Welsh Corgi                           9
Irish Setter                                   8
Samoyed                                        8
Galgo Spanish Greyhound                        8
Boerboel                                       8
Smooth Collie                                  8
Eskimo Dog                                     8
German Pinscher                                7
Greater Swiss Mountain Dog                     7
Borzoi                                         6
Bearded Collie                                 6
Norwich Terrier                                6
Rough Collie                                   6
Norwegian Elkhound                             6
Giant Schnauzer                                6
Nova Scotia Duck Tolling Retriever             5
Finnish Spitz                                  5
Lakeland Terrier                               5
McNab                                          5
Ibizan Hound                                   5
Norfolk Terrier                                5
American Hairless Terrier                      4
Keeshond                                       4
Lancashire Heeler                              4
English Foxhound                               4
Smooth Fox Terrier                             4
Wirehaired Dachshund                           4
Afghan Hound                                   4
Portuguese Podengo                             4
Beauceron                                      4
Clumber Spaniel                                4
Maremma Sheepdog                               4
Tibetan Terrier                                3
Thai Ridgeback                                 3
Miniature Dachshund                            3
Akbash                                         3
Sheep Dog                                      3
Belgian Shepherd / Sheepdog                    3
Caucasian Sheepdog / Caucasian Ovtcharka       3
English Cocker Spaniel                         2
Kyi Leo                                        2
Coton de Tulear                                2
Curly-Coated Retriever                         2
Gordon Setter                                  2
Entlebucher                                    2
German Spitz                                   2
Norwegian Buhund                               2
Belgian Shepherd / Tervuren                    2
Otterhound                                     2
Bouvier des Flandres                           1
Kai Dog                                        1
Skye Terrier                                   1
Chinese Foo Dog                                1
Kuvasz                                         1
Bolognese                                      1
Fila Brasileiro                                1
Spinone Italiano                               1
Briard                                         1
Leonberger                                     1
Field Spaniel                                  1
Chinook                                        1
Wirehaired Pointing Griffon                    1
Boykin Spaniel                                 1
Old English Sheepdog                           1
Belgian Shepherd / Laekenois                   1
Tosa Inu                                       1
Name: breed_primary, dtype: int64

### 3. For each (primary) breed, determine the ratio between the number of dogs of Mixed Breed and those not of Mixed Breed

In [6]:
breed_secondary   = df['breed_secondary'].value_counts()




df_grouped = df.groupby(['breed_primary', 'breed_secondary']).size().reset_index(name='count')


# Define the year to filter
breed_to_filter = 'Mixed Breed'

# Filter rows based on the year
df_Mixed = df_grouped[df_grouped['breed_secondary'] == breed_to_filter]

# Sort the filtered DataFrame by count in descending order
df_Mixed_sorted = df_Mixed.sort_values(by='count', ascending=False)

print(f"Number of Mixed Breed Dogs is: {df_Mixed_sorted['count'].sum()}")



df_Not_Mixed = df_grouped[df_grouped['breed_secondary'] != breed_to_filter]
df_Not_Mixed_sorted = df_Not_Mixed.sort_values(by='count', ascending=False)
# print(df_sum[df_sum['breed_secondary'] == breed_to_filter]['total_count'].values[0])

# Print the sorted filtered DataFrame
print(f"Number of Not Mixed Breed Dogs hs: {df_Not_Mixed_sorted['count'].sum()}")

print(df_Mixed_sorted)

Number of Mixed Breed Dogs is: 4348
Number of Not Mixed Breed Dogs hs: 16473
                             breed_primary breed_secondary  count
2138                      Pit Bull Terrier     Mixed Breed   1151
1832                    Labrador Retriever     Mixed Breed    616
2770                               Terrier     Mixed Breed    263
924                              Chihuahua     Mixed Breed    190
1612                                 Hound     Mixed Breed    189
1404                   German Shepherd Dog     Mixed Breed    189
2556                              Shepherd     Mixed Breed    157
677                                  Boxer     Mixed Breed    143
131         American Staffordshire Terrier     Mixed Breed    110
70                        American Bulldog     Mixed Breed    106
2362                             Retriever     Mixed Breed     82
382                                 Beagle     Mixed Breed     80
201    Australian Cattle Dog / Blue Heeler     Mixed Breed     72
581                          Border Collie     Mixed Breed     50
2409                            Rottweiler     Mixed Breed     40
872                             Cattle Dog     Mixed Breed     38
1128                             Dachshund     Mixed Breed     36
2706            Staffordshire Bull Terrier     Mixed Breed     36
1660                                 Husky     Mixed Breed     31
2499                              Shar-Pei     Mixed Breed     31
2213                               Pointer     Mixed Breed     31
835                  Catahoula Leopard Dog     Mixed Breed     30
1950                    Miniature Pinscher     Mixed Breed     28
2641                        Siberian Husky     Mixed Breed     27
2178                           Plott Hound     Mixed Breed     27
1924                               Mastiff     Mixed Breed     26
271                    Australian Shepherd     Mixed Breed     24
2059                Parson Russell Terrier     Mixed Breed     21
997                              Chow Chow     Mixed Breed     20
487                        Black Mouth Cur     Mixed Breed     19
2614                              Shih Tzu     Mixed Breed     17
2255                                Poodle     Mixed Breed     15
2946                     Yorkshire Terrier     Mixed Breed     15
331                           Basset Hound     Mixed Breed     14
2313                           Rat Terrier     Mixed Breed     14
2821              Treeing Walker Coonhound     Mixed Breed     13
459               Black Labrador Retriever     Mixed Breed     13
2286                                   Pug     Mixed Breed     13
1048                                Collie     Mixed Breed     12
1534                        Great Pyrenees     Mixed Breed     11
1071                             Coonhound     Mixed Breed     11
1178                     Doberman Pinscher     Mixed Breed     11
731                           Bull Terrier     Mixed Breed     10
2462                             Schnauzer     Mixed Breed     10
230                      Australian Kelpie     Mixed Breed      9
164                     Anatolian Shepherd     Mixed Breed      9
1885                               Maltese     Mixed Breed      9
2600                             Shiba Inu     Mixed Breed      8
2665                               Spaniel     Mixed Breed      8
2233                            Pomeranian     Mixed Breed      7
630                         Boston Terrier     Mixed Breed      7
507                Black and Tan Coonhound     Mixed Breed      7
414            Belgian Shepherd / Malinois     Mixed Breed      7
27                                   Akita     Mixed Breed      6
757                          Cairn Terrier     Mixed Breed      6
1559                             Greyhound     Mixed Breed      6
2335                     Redbone Coonhound     Mixed Breed      6
1469                      Golden Retriever     Mixed Breed      6
2011                          Mountain Cur     Mixed Breed      6
1501                            Great Dane     Mixed Breed      5
1729                  Jack Russell Terrier     Mixed Breed      5
2721                    Standard Schnauzer     Mixed Breed      5
791                   Cardigan Welsh Corgi     Mixed Breed      5
1439            German Shorthaired Pointer     Mixed Breed      5
1236                     English Coonhound     Mixed Breed      5
1223                       English Bulldog     Mixed Breed      5
1159                             Dalmatian     Mixed Breed      5
2382                   Rhodesian Ridgeback     Mixed Breed      5
2431                         Saint Bernard     Mixed Breed      5
780                             Cane Corso     Mixed Breed      5
1289                                 Feist     Mixed Breed      5
2045                              Papillon     Mixed Breed      4
304                                Basenji     Mixed Breed      4
36                        Alaskan Malamute     Mixed Breed      4
2903                    Wirehaired Terrier     Mixed Breed      4
2680                                 Spitz     Mixed Breed      4
1903                    Manchester Terrier     Mixed Breed      4
1321                           Fox Terrier     Mixed Breed      4
1093                                 Corgi     Mixed Breed      4
1335                              Foxhound     Mixed Breed      4
807                           Carolina Dog     Mixed Breed      4
520                             Bloodhound     Mixed Breed      4
536                     Bluetick Coonhound     Mixed Breed      4
2850                            Weimaraner     Mixed Breed      4
1196                     Dogue de Bordeaux     Mixed Breed      4
1700                     Italian Greyhound     Mixed Breed      3
745                            Bullmastiff     Mixed Breed      3
604                         Border Terrier     Mixed Breed      3
2799                       Tibetan Mastiff     Mixed Breed      3
1022                        Cocker Spaniel     Mixed Breed      3
2880                               Whippet     Mixed Breed      3
1206                        Dutch Shepherd     Mixed Breed      3
86                     American Eskimo Dog     Mixed Breed      2
1875                            Lhasa Apso     Mixed Breed      2
2270                         Presa Canario     Mixed Breed      2
1258                      English Shepherd     Mixed Breed      2
2448                            Schipperke     Mixed Breed      2
97               American Hairless Terrier     Mixed Breed      2
2589           Shetland Sheepdog / Sheltie     Mixed Breed      2
2835                                Vizsla     Mixed Breed      2
2085                         Pharaoh Hound     Mixed Breed      2
2070                             Pekingese     Mixed Breed      2
2066     Patterdale Terrier / Fell Terrier     Mixed Breed      2
1447             German Wirehaired Pointer     Mixed Breed      2
2031                      Norwegian Buhund     Mixed Breed      2
1962                   Miniature Schnauzer     Mixed Breed      2
427                           Bichon Frise     Mixed Breed      2
2808                       Toy Fox Terrier     Mixed Breed      1
2800                       Tibetan Spaniel     Mixed Breed      1
2897                  Wirehaired Dachshund     Mixed Breed      1
2655                    Smooth Fox Terrier     Mixed Breed      1
2861  West Highland White Terrier / Westie     Mixed Breed      1
2865                       Wheaten Terrier     Mixed Breed      1
2718                       Standard Poodle     Mixed Breed      1
1                            Affenpinscher     Mixed Breed      1
2508                             Sheep Dog     Mixed Breed      1
2079          Petit Basset Griffon Vendeen     Mixed Breed      1
420                   Bernese Mountain Dog     Mixed Breed      1
611                                 Borzoi     Mixed Breed      1
713                       Brussels Griffon     Mixed Breed      1
896               Chesapeake Bay Retriever     Mixed Breed      1
973           Chocolate Labrador Retriever     Mixed Breed      1
1247                       English Pointer     Mixed Breed      1
1266                           Entlebucher     Mixed Breed      1
1307                 Flat-Coated Retriever     Mixed Breed      1
1348                        French Bulldog     Mixed Breed      1
1357                       German Pinscher     Mixed Breed      1
1481                         Gordon Setter     Mixed Breed      1
8                         Airedale Terrier     Mixed Breed      1
1682                         Irish Terrier     Mixed Breed      1
1688                       Irish Wolfhound     Mixed Breed      1
1872                     Lancashire Heeler     Mixed Breed      1
1937                   Miniature Dachshund     Mixed Breed      1
2026                      Newfoundland Dog     Mixed Breed      1
2029                       Norfolk Terrier     Mixed Breed      1
2033                    Norwegian Elkhound     Mixed Breed      1
2037                       Norwich Terrier     Mixed Breed      1
2040                            Otterhound     Mixed Breed      1
1573                              Havanese     Mixed Breed      1

### 4. For each (primary) breed, determine the earliest and the latest posted timestamp.

In [7]:
# Group the DataFrame by breed_primary and find the earliest and the latest posted timestamp
df_grouped = df.groupby('breed_primary')['posted'].agg(['min', 'max'])

# Print the result
print(df_grouped)

                                                               min  \
breed_primary
Affenpinscher                             2012-03-08T10:27:33+0000
Afghan Hound                              2017-06-29T23:28:51+0000
Airedale Terrier                          2014-06-13T12:59:36+0000
Akbash                                    2019-07-21T00:35:59+0000
Akita                                     2012-03-03T09:31:08+0000
Alaskan Malamute                          2015-02-24T13:18:06+0000
American Bulldog                          2009-03-11T00:00:00+0000
American Eskimo Dog                       2017-04-27T18:39:24+0000
American Foxhound                         2019-02-06T03:06:20+0000
American Hairless Terrier                 2013-07-03T10:05:41+0000
American Staffordshire Terrier            2007-10-07T00:00:00+0000
Anatolian Shepherd                        2014-03-12T08:36:07+0000
Australian Cattle Dog / Blue Heeler       2010-11-13T00:00:00+0000
Australian Kelpie                         2011-07-31T07:32:36+0000
Australian Shepherd                       2008-11-06T00:00:00+0000
Australian Terrier                        2017-02-17T16:34:02+0000
Basenji                                   2009-10-15T00:00:00+0000
Basset Hound                              2011-11-11T13:27:32+0000
Beagle                                    2003-05-18T00:00:00+0000
Bearded Collie                            2018-06-08T06:57:28+0000
Beauceron                                 2019-09-05T18:52:36+0000
Belgian Shepherd / Laekenois              2019-09-03T22:01:52+0000
Belgian Shepherd / Malinois               2014-04-05T20:03:13+0000
Belgian Shepherd / Sheepdog               2019-07-19T14:20:19+0000
Belgian Shepherd / Tervuren               2017-03-31T21:34:30+0000
Bernese Mountain Dog                      2018-06-22T20:14:31+0000
Bichon Frise                              2018-04-08T13:02:19+0000
Black Labrador Retriever                  2008-06-25T00:00:00+0000
Black Mouth Cur                           2009-10-15T00:00:00+0000
Black and Tan Coonhound                   2013-07-29T01:49:30+0000
Bloodhound                                2009-07-31T00:00:00+0000
Blue Lacy                                 2018-08-21T22:02:49+0000
Bluetick Coonhound                        2010-03-18T00:00:00+0000
Boerboel                                  2016-11-06T21:22:40+0000
Bolognese                                 2019-09-14T21:06:30+0000
Border Collie                             2008-02-08T00:00:00+0000
Border Terrier                            2015-02-08T15:37:13+0000
Borzoi                                    2019-05-06T20:46:28+0000
Boston Terrier                            2009-03-23T00:00:00+0000
Bouvier des Flandres                      2019-09-20T09:54:21+0000
Boxer                                     2005-05-30T00:00:00+0000
Boykin Spaniel                            2019-09-16T20:11:19+0000
Briard                                    2019-05-27T20:55:54+0000
Brittany Spaniel                          2012-07-30T12:48:04+0000
Brussels Griffon                          2015-07-11T01:29:10+0000
Bull Terrier                              2011-12-02T18:47:41+0000
Bullmastiff                               2015-05-26T00:21:37+0000
Cairn Terrier                             2010-07-07T00:00:00+0000
Canaan Dog                                2015-05-11T12:05:18+0000
Cane Corso                                2015-11-02T18:23:55+0000
Cardigan Welsh Corgi                      2018-09-24T02:10:03+0000
Carolina Dog                              2009-04-16T00:00:00+0000
Catahoula Leopard Dog                     2010-07-05T00:00:00+0000
Cattle Dog                                2009-04-16T00:00:00+0000
Caucasian Sheepdog / Caucasian Ovtcharka  2019-01-05T16:55:30+0000
Cavalier King Charles Spaniel             2015-03-19T12:29:00+0000
Chesapeake Bay Retriever                  2014-09-12T09:51:10+0000
Chihuahua                                 2007-11-11T00:00:00+0000
Chinese Crested Dog                       2015-06-22T09:18:28+0000
Chinese Foo Dog                           2019-09-13T10:30:17+0000
Chinook                                   2019-01-31T02:12:18+0000
Chocolate Labrador Retriever              2005-10-08T00:00:00+0000
Chow Chow                                 2011-09-18T13:42:46+0000
Clumber Spaniel                           2019-06-19T20:40:51+0000
Cockapoo                                  2018-09-14T10:28:44+0000
Cocker Spaniel                            2007-06-04T00:00:00+0000
Collie                                    2010-08-05T00:00:00+0000
Coonhound                                 2010-07-21T00:00:00+0000
Corgi                                     2009-10-06T00:00:00+0000
Coton de Tulear                           2019-05-12T19:24:46+0000
Curly-Coated Retriever                    2017-01-13T05:08:23+0000
Dachshund                                 2010-07-16T00:00:00+0000
Dalmatian                                 2004-02-29T00:00:00+0000
Doberman Pinscher                         2009-06-16T00:00:00+0000
Dogo Argentino                            2016-05-11T15:55:04+0000
Dogue de Bordeaux                         2018-10-09T16:16:14+0000
Dutch Shepherd                            2011-09-28T19:29:38+0000
English Bulldog                           2012-11-20T13:48:45+0000
English Cocker Spaniel                    2019-07-30T07:18:10+0000
English Coonhound                         2014-02-11T21:42:31+0000
English Foxhound                          2019-06-16T21:07:46+0000
English Pointer                           2015-06-10T20:16:51+0000
English Setter                            2018-11-24T15:30:58+0000
English Shepherd                          2015-10-23T03:26:28+0000
English Springer Spaniel                  2017-05-18T02:21:44+0000
Entlebucher                               2018-05-28T16:19:05+0000
Eskimo Dog                                2018-08-25T02:59:41+0000
Feist                                     2010-09-07T00:00:00+0000
Field Spaniel                             2019-09-20T00:02:45+0000
Fila Brasileiro                           2018-11-26T22:44:11+0000
Finnish Spitz                             2019-04-22T00:39:42+0000
Flat-Coated Retriever                     2018-08-03T15:41:00+0000
Fox Terrier                               2017-04-06T20:17:45+0000
Foxhound                                  2008-02-13T00:00:00+0000
French Bulldog                            2014-10-27T14:57:14+0000
Galgo Spanish Greyhound                   2019-03-03T23:27:30+0000
German Pinscher                           2013-10-11T17:07:51+0000
German Shepherd Dog                       2006-10-05T00:00:00+0000
German Shorthaired Pointer                2008-09-10T00:00:00+0000
German Spitz                              2019-07-27T00:45:47+0000
German Wirehaired Pointer                 2017-03-27T16:17:11+0000
Giant Schnauzer                           2018-12-03T20:38:42+0000
Golden Retriever                          2007-02-13T00:00:00+0000
Gordon Setter                             2019-07-31T17:27:03+0000
Great Dane                                2008-09-08T00:00:00+0000
Great Pyrenees                            2008-05-31T00:00:00+0000
Greater Swiss Mountain Dog                2018-07-30T12:24:59+0000
Greyhound                                 2005-09-26T00:00:00+0000
Harrier                                   2016-03-07T07:27:51+0000
Havanese                                  2016-09-14T07:00:30+0000
Hound                                     2009-11-18T00:00:00+0000
Husky                                     2008-06-11T00:00:00+0000
Ibizan Hound                              2015-05-15T13:00:01+0000
Irish Setter                              2019-06-05T15:42:38+0000
Irish Terrier                             2016-05-03T12:24:11+0000
Irish Wolfhound                           2014-02-10T08:51:37+0000
Italian Greyhound                         2013-04-04T13:23:29+0000
Jack Russell Terrier                      2011-01-03T11:06:01+0000
Japanese Chin                             2010-05-04T00:00:00+0000
Jindo                                     2016-01-20T20:10:40+0000
Kai Dog                                   2019-06-13T17:02:37+0000
Keeshond                                  2017-06-11T18:13:23+0000
Kuvasz                                    2019-09-07T17:53:45+0000
Kyi Leo                                   2019-08-23T00:02:39+0000
Labrador Retriever                        2006-12-28T00:00:00+0000
Lakeland Terrier                          2019-09-01T04:44:34+0000
Lancashire Heeler                         2019-04-05T14:59:30+0000
Leonberger                                2017-07-05T08:06:13+0000
Lhasa Apso                                2010-09-02T00:00:00+0000
Maltese                                   2013-05-11T13:50:59+0000
Manchester Terrier                        2017-04-03T21:10:56+0000
Maremma Sheepdog                          2016-01-05T01:32:55+0000
Mastiff                                   2010-03-13T00:00:00+0000
McNab                                     2015-06-29T19:54:12+0000
Miniature Dachshund                       2018-11-04T21:45:30+0000
Miniature Pinscher                        2006-04-20T00:00:00+0000
Miniature Poodle                          2018-12-09T22:50:49+0000
Miniature Schnauzer                       2018-01-16T04:17:54+0000
Mixed Breed                               2014-10-27T14:45:16+0000
Mountain Cur                              2012-08-30T21:58:53+0000
Mountain Dog                              2019-03-17T05:23:31+0000
Neapolitan Mastiff                        2016-10-10T22:14:24+0000
Newfoundland Dog                          2017-08-12T23:43:07+0000
Norfolk Terrier                           2017-12-08T23:59:12+0000
Norwegian Buhund                          2019-07-04T16:54:50+0000
Norwegian Elkhound                        2010-03-18T00:00:00+0000
Norwich Terrier                           2019-04-11T01:03:56+0000
Nova Scotia Duck Tolling Retriever        2019-04-17T02:02:39+0000
Old English Sheepdog                      2019-08-22T14:39:21+0000
Otterhound                                2008-03-14T00:00:00+0000
Papillon                                  2014-06-14T13:33:41+0000
Parson Russell Terrier                    2006-01-31T00:00:00+0000
Patterdale Terrier / Fell Terrier         2019-03-23T02:04:24+0000
Pekingese                                 2009-02-21T00:00:00+0000
Pembroke Welsh Corgi                      2019-06-18T21:24:56+0000
Petit Basset Griffon Vendeen              2017-10-18T15:53:16+0000
Pharaoh Hound                             2018-03-06T00:40:26+0000
Pit Bull Terrier                          2007-01-11T00:00:00+0000
Plott Hound                               2011-01-01T22:33:18+0000
Pointer                                   2010-04-05T00:00:00+0000
Pomeranian                                2013-01-29T09:32:11+0000
Poodle                                    2011-02-03T16:25:46+0000
Portuguese Podengo                        2019-01-31T18:03:01+0000
Presa Canario                             2016-10-08T18:20:52+0000
Pug                                       2010-10-09T00:00:00+0000
Rat Terrier                               2005-10-03T00:00:00+0000
Redbone Coonhound                         2011-09-13T20:40:00+0000
Retriever                                 2011-01-01T13:33:56+0000
Rhodesian Ridgeback                       2010-07-23T00:00:00+0000
Rottweiler                                2009-11-19T00:00:00+0000
Rough Collie                              2017-12-05T12:07:40+0000
Saint Bernard                             2012-06-07T16:20:39+0000
Saluki                                    2018-02-14T22:10:07+0000
Samoyed                                   2019-03-16T18:06:37+0000
Schipperke                                2018-01-22T00:06:07+0000
Schnauzer                                 2011-10-22T16:51:30+0000
Scottish Terrier                          2015-02-02T15:48:08+0000
Setter                                    2017-04-17T15:41:41+0000
Shar-Pei                                  2009-01-13T00:00:00+0000
Sheep Dog                                 2019-03-20T16:26:48+0000
Shepherd                                  2006-02-23T00:00:00+0000
Shetland Sheepdog / Sheltie               2016-07-10T09:37:04+0000
Shiba Inu                                 2016-02-22T23:53:06+0000
Shih Tzu                                  2008-09-25T00:00:00+0000
Siberian Husky                            2011-01-14T21:58:52+0000
Silky Terrier                             2018-07-17T23:01:48+0000
Skye Terrier                              2019-01-18T19:51:21+0000
Smooth Collie                             2019-01-16T15:10:45+0000
Smooth Fox Terrier                        2011-11-15T04:00:50+0000
Spaniel                                   2007-06-18T00:00:00+0000
Spinone Italiano                          2019-09-13T19:49:38+0000
Spitz                                     2011-03-28T20:15:41+0000
Staffordshire Bull Terrier                2008-03-20T00:00:00+0000
Standard Poodle                           2018-07-17T23:01:48+0000
Standard Schnauzer                        2018-10-08T02:38:55+0000
Terrier                                   2006-10-17T00:00:00+0000
Thai Ridgeback                            2019-04-10T16:42:47+0000
Tibetan Mastiff                           2018-10-06T22:09:26+0000
Tibetan Spaniel                           2012-10-04T16:24:58+0000
Tibetan Terrier                           2019-08-18T17:03:34+0000
Tosa Inu                                  2019-09-04T00:48:24+0000
Toy Fox Terrier                           2013-12-12T20:05:04+0000
Treeing Walker Coonhound                  2009-03-03T00:00:00+0000
Vizsla                                    2016-06-13T22:14:52+0000
Weimaraner                                2012-05-24T12:32:25+0000
West Highland White Terrier / Westie      2008-03-31T00:00:00+0000
Wheaten Terrier                           2018-06-25T19:37:22+0000
Whippet                                   2017-01-27T17:25:06+0000
White German Shepherd                     2016-09-03T00:21:06+0000
Wire Fox Terrier                          2013-12-11T17:08:03+0000
Wirehaired Dachshund                      2019-04-08T23:12:04+0000
Wirehaired Pointing Griffon               2016-06-29T20:03:55+0000
Wirehaired Terrier                        2012-11-27T14:07:54+0000
Xoloitzcuintli / Mexican Hairless         2007-02-01T00:00:00+0000
Yellow Labrador Retriever                 2010-05-31T00:00:00+0000
Yorkshire Terrier                         2012-02-04T17:14:52+0000

                                                               max
breed_primary
Affenpinscher                             2019-09-14T10:10:51+0000
Afghan Hound                              2019-07-27T00:38:48+0000
Airedale Terrier                          2019-09-19T18:40:39+0000
Akbash                                    2019-08-23T17:11:04+0000
Akita                                     2019-09-20T15:19:57+0000
Alaskan Malamute                                        Gettysburg
American Bulldog                                        Saugerties
American Eskimo Dog                       2019-09-20T00:15:25+0000
American Foxhound                         2019-09-18T22:21:39+0000
American Hairless Terrier                 2019-09-17T20:06:53+0000
American Staffordshire Terrier                         Mooresville
Anatolian Shepherd                        2019-09-20T13:36:10+0000
Australian Cattle Dog / Blue Heeler       2019-09-20T16:31:13+0000
Australian Kelpie                         2019-09-20T02:18:47+0000
Australian Shepherd                                           Ross
Australian Terrier                        2019-09-18T22:30:47+0000
Basenji                                   2019-09-19T22:16:30+0000
Basset Hound                                                Albany
Beagle                                                      Albany
Bearded Collie                            2019-09-16T10:09:34+0000
Beauceron                                 2019-09-20T03:27:37+0000
Belgian Shepherd / Laekenois              2019-09-03T22:01:52+0000
Belgian Shepherd / Malinois               2019-09-20T06:05:22+0000
Belgian Shepherd / Sheepdog               2019-09-17T20:34:08+0000
Belgian Shepherd / Tervuren               2019-09-02T15:58:23+0000
Bernese Mountain Dog                      2019-09-20T14:30:30+0000
Bichon Frise                              2019-09-19T02:28:13+0000
Black Labrador Retriever                  2019-09-20T06:31:10+0000
Black Mouth Cur                           2019-09-20T16:14:51+0000
Black and Tan Coonhound                   2019-09-19T20:17:24+0000
Bloodhound                                2019-09-18T14:49:41+0000
Blue Lacy                                 2019-09-20T13:19:51+0000
Bluetick Coonhound                        2019-09-20T16:29:04+0000
Boerboel                                  2019-09-18T02:32:39+0000
Bolognese                                 2019-09-14T21:06:30+0000
Border Collie                             2019-09-20T16:44:30+0000
Border Terrier                            2019-09-20T03:21:30+0000
Borzoi                                    2019-09-18T20:06:58+0000
Boston Terrier                            2019-09-20T10:02:48+0000
Bouvier des Flandres                      2019-09-20T09:54:21+0000
Boxer                                                     Chandler
Boykin Spaniel                            2019-09-16T20:11:19+0000
Briard                                    2019-05-27T20:55:54+0000
Brittany Spaniel                          2019-09-19T13:07:03+0000
Brussels Griffon                          2019-09-20T13:19:46+0000
Bull Terrier                              2019-09-20T15:06:16+0000
Bullmastiff                               2019-09-20T16:19:55+0000
Cairn Terrier                             2019-09-20T10:07:25+0000
Canaan Dog                                2019-09-17T23:11:56+0000
Cane Corso                                2019-09-20T15:30:52+0000
Cardigan Welsh Corgi                      2019-09-20T01:18:36+0000
Carolina Dog                              2019-09-19T21:06:44+0000
Catahoula Leopard Dog                     2019-09-20T16:19:36+0000
Cattle Dog                                2019-09-20T16:28:05+0000
Caucasian Sheepdog / Caucasian Ovtcharka  2019-09-04T14:48:19+0000
Cavalier King Charles Spaniel             2019-09-19T21:59:10+0000
Chesapeake Bay Retriever                  2019-09-20T00:18:28+0000
Chihuahua                                                  Seattle
Chinese Crested Dog                       2019-09-19T20:06:20+0000
Chinese Foo Dog                           2019-09-13T10:30:17+0000
Chinook                                   2019-01-31T02:12:18+0000
Chocolate Labrador Retriever              2019-09-20T07:24:20+0000
Chow Chow                                 2019-09-19T17:06:38+0000
Clumber Spaniel                           2019-09-16T21:04:14+0000
Cockapoo                                  2019-09-20T14:29:47+0000
Cocker Spaniel                            2019-09-20T17:20:30+0000
Collie                                    2019-09-20T15:20:02+0000
Coonhound                                 2019-09-20T10:02:48+0000
Corgi                                     2019-09-20T08:21:47+0000
Coton de Tulear                           2019-07-08T14:34:25+0000
Curly-Coated Retriever                    2019-05-23T12:33:12+0000
Dachshund                                 2019-09-20T16:28:40+0000
Dalmatian                                 2019-09-19T23:45:43+0000
Doberman Pinscher                         2019-09-20T16:06:34+0000
Dogo Argentino                            2019-09-20T03:50:26+0000
Dogue de Bordeaux                         2019-09-14T10:40:49+0000
Dutch Shepherd                            2019-09-20T10:13:39+0000
English Bulldog                           2019-09-19T23:47:36+0000
English Cocker Spaniel                    2019-09-18T22:57:37+0000
English Coonhound                         2019-09-20T10:02:48+0000

### 5. For each state, compute the sex imbalance, that is the difference between male and female dogs. In which state this imbalance is largest?

In [8]:
counts = df.groupby(['contact_state', 'sex']).size().reset_index(name='count')
pivoted = counts.pivot(index='contact_state', columns='sex', values='count')
pivoted['imbalance'] = abs(pivoted['Male'] - pivoted['Female'])

# print the pivoted DataFrame
print(pivoted.sort_values(by='imbalance', ascending=False))

sex            Female    Male  Unknown  imbalance
contact_state
OH             1231.0  1439.0      NaN      208.0
IN              850.0  1027.0      NaN      177.0
VA             1450.0  1608.0      NaN      158.0
MD              679.0   814.0      NaN      135.0
TN              825.0   944.0      NaN      119.0
NY             1943.0  2059.0      NaN      116.0
AZ             1066.0  1181.0      1.0      115.0
CA              777.0   887.0      NaN      110.0
KY              507.0   616.0      NaN      109.0
WV              232.0   333.0      NaN      101.0
FL             1279.0  1380.0      NaN      101.0
IL              507.0   607.0      NaN      100.0
SC              759.0   859.0      NaN      100.0
WA              595.0   682.0      NaN       87.0
PA             1368.0  1453.0      NaN       85.0
IA              202.0   283.0      NaN       81.0
UT              203.0   282.0      NaN       79.0
MO              425.0   495.0      NaN       70.0
NC             1282.0  1345.0      NaN       63.0
CT              682.0   740.0      NaN       58.0
NJ             1483.0  1539.0      NaN       56.0
NV              402.0   455.0      NaN       53.0
CO              912.0   861.0      NaN       51.0
VT              234.0   276.0      NaN       42.0
MS              275.0   235.0      NaN       40.0
MI              317.0   356.0      NaN       39.0
MN              462.0   496.0      NaN       34.0
ME              287.0   258.0      NaN       29.0
MA              459.0   487.0      NaN       28.0
OR               33.0    58.0      NaN       25.0
GA             1727.0  1752.0      NaN       25.0
LA              444.0   466.0      2.0       22.0
NM              309.0   327.0      NaN       18.0
DC              176.0   160.0      NaN       16.0
HI               28.0    41.0      NaN       13.0
WI              265.0   277.0      NaN       12.0
SD                7.0    17.0      NaN       10.0
WY               21.0    31.0      NaN       10.0
NH              172.0   163.0      NaN        9.0
TX              287.0   279.0      NaN        8.0
ND               28.0    36.0      NaN        8.0
OK              814.0   822.0      NaN        8.0
AR              351.0   344.0      NaN        7.0
RI              306.0   301.0      NaN        5.0
MT                7.0    11.0      NaN        4.0
AL              716.0   712.0      NaN        4.0
NE               61.0    59.0      NaN        2.0
98106             3.0     4.0      NaN        1.0
AK                7.0     8.0      NaN        1.0
12220             1.0     2.0      NaN        1.0
ID               24.0    25.0      NaN        1.0
DE              148.0   148.0      NaN        0.0
12477             1.0     1.0      NaN        0.0
QC                7.0     7.0      NaN        0.0
NB                1.0     1.0      NaN        0.0
17325             1.0     1.0      NaN        0.0
KS              235.0   235.0      NaN        0.0
19053             1.0     NaN      NaN        NaN
19063             1.0     NaN      NaN        NaN
20136             1.0     NaN      NaN        NaN
20905             NaN     1.0      NaN        NaN
23112             NaN     1.0      NaN        NaN
24588             NaN     1.0      NaN        NaN
37189             1.0     NaN      NaN        NaN
38506             NaN     1.0      NaN        NaN
45061             2.0     NaN      NaN        NaN
45249             1.0     NaN      NaN        NaN
46158             1.0     NaN      NaN        NaN
47131             NaN     1.0      NaN        NaN
47454             NaN     1.0      NaN        NaN
61944             NaN     1.0      NaN        NaN
70601             NaN     1.0      NaN        NaN
85249             1.0     NaN      NaN        NaN
87108             1.0     NaN      NaN        NaN
89146             NaN     1.0      NaN        NaN

### So the Largest imbalance is related to OH

### 6. For each pair (age, size), determine the average duration of the stay and the average cost of stay.

In [10]:
# Group the DataFrame by age and size and calculate the mean stay_duration for each group

df_grouped1 = df.groupby(['age', 'size'])['stay_duration'].mean()

# Reset the index to move the 'age' and 'gender' columns back to regular columns
df_grouped1 = df_grouped1.reset_index()

# Print the result
print(df_grouped1)

       age         size  stay_duration
0    Adult  Extra Large      89.015414
1    Adult        Large      89.531943
2    Adult       Medium      89.421036
3    Adult        Small      89.407479
4     Baby  Extra Large      87.032967
5     Baby        Large      89.701564
6     Baby       Medium      89.577668
7     Baby        Small      89.958291
8   Senior  Extra Large      88.861111
9   Senior        Large      88.984298
10  Senior       Medium      89.810052
11  Senior        Small      89.073626
12   Young  Extra Large      90.586345
13   Young        Large      90.104206
14   Young       Medium      89.515123
15   Young        Small      89.814275

In [11]:
# Group the DataFrame by age and size and calculate the mean stay_cost for each group

df_grouped2 = df.groupby(['age', 'size'])['stay_cost'].mean()

# Reset the index to move the 'age' and 'size' columns back to regular columns
df_grouped2 = df_grouped2.reset_index()

# Print the result
print(df_grouped2)

       age         size   stay_cost
0    Adult  Extra Large  232.591561
1    Adult        Large  238.661141
2    Adult       Medium  238.258977
3    Adult        Small  238.974838
4     Baby  Extra Large  237.180879
5     Baby        Large  238.698827
6     Baby       Medium  237.108131
7     Baby        Small  239.083810
8   Senior  Extra Large  235.232361
9   Senior        Large  237.507364
10  Senior       Medium  238.514615
11  Senior        Small  238.282286
12   Young  Extra Large  245.835582
13   Young        Large  238.149506
14   Young       Medium  239.304603
15   Young        Small  241.540069

### 7. Find the dogs involved in at least 3 travels. Also list the breed of those dogs.
<br>
<br>
The dataset consist of each travel for dogs. each dog has a unigue ID , so we can count the number of travels based on the ID.<br>
after detemining the number of travels for each dog in this dataset, we can join the results from this dataset with the original dataset based on the ID.

In [12]:
df2 = pd.read_csv('dataset/dogTravel.csv')

id_counts = df2['id'].value_counts()

# Filter the result to only include id of dogs with at least 3 travels
id_counts_filtered = id_counts[id_counts > 2]


# Create a new DataFrame from the result of value_counts() and rename the columns
id_counts_df = pd.DataFrame({'id': id_counts_filtered.index, 'travels': id_counts_filtered.values})

# print(id_counts_df)


# Join the filtered dogs with the breed dataset on the 'dog_id' column
filtered_dogs_breed = pd.merge(id_counts_df, df, on='id')

# print(filtered_dogs_breed)

result_df =filtered_dogs_breed[['id', 'travels','breed_primary' ]]

# Print the result
print(result_df)

           id  travels                         breed_primary
0    44759409       11                   German Shepherd Dog
1    44759410       11                   German Shepherd Dog
2    36978896        7                      Alaskan Malamute
3    44572953        7                      Alaskan Malamute
4    45537987        7                      Alaskan Malamute
5    45728583        7                      Alaskan Malamute
6    45988387        7                      Alaskan Malamute
7    33218331        7                      Alaskan Malamute
8    44070616        7                      Alaskan Malamute
9    45675487        5                    Labrador Retriever
10   45922866        5                 Catahoula Leopard Dog
11   45922399        5                   German Shepherd Dog
12   45922400        5                   German Shepherd Dog
13   45922493        5                   German Shepherd Dog
14   45922496        5                   German Shepherd Dog
15   45922494        5                      English Shepherd
16   45922495        5                   German Shepherd Dog
17   45922864        5                   German Shepherd Dog
18   45922963        5                   German Shepherd Dog
19   45923720        5                               Terrier
20   45922964        5                   German Shepherd Dog
21   45922965        5                               Pointer
22   45922966        5                   German Shepherd Dog
23   45923050        5                   German Shepherd Dog
24   45923051        5                   German Shepherd Dog
25   45923722        5                               Terrier
26   45923716        5                               Terrier
27   45922401        5                   German Shepherd Dog
28   45922330        5                       Irish Wolfhound
29   45922329        5                   German Shepherd Dog
30   45922328        5                               Pointer
31   45954988        5                                 Husky
32   45954994        5                                 Husky
33   45954993        5                                 Husky
34   45954989        5                                 Husky
35   45062296        5                        Great Pyrenees
36   45062301        5                               Pointer
37   45062315        5                      Pit Bull Terrier
38   45062319        5                      Pit Bull Terrier
39   45062325        5                      Pit Bull Terrier
40   45062298        5                    Labrador Retriever
41   45062308        5                              Shepherd
42   45282250        5                             Chihuahua
43   45655743        5                             Dachshund
44   45835627        5                              Shih Tzu
45   45922203        5                    Labrador Retriever
46   45923717        5                               Terrier
47   45923714        5                             Retriever
48   20905974        5                             Chow Chow
49   45929227        5                             Retriever
50   45954990        5                                 Husky
51   45954992        5                                 Husky
52   45991032        5                    Labrador Retriever
53   45982956        5              Black Labrador Retriever
54   45982927        5                            Cattle Dog
55   45929298        5              Black Labrador Retriever
56   45929258        5                             Retriever
57   45880454        5                               Pointer
58   45923718        5                               Terrier
59   45880427        5                               Pointer
60   45860138        5                     Redbone Coonhound
61   45859953        5                    Labrador Retriever
62   45670129        5                              Papillon
63   45263815        5                            Great Dane
64   45978369        5                     Doberman Pinscher
65   42445043        5                        Dutch Shepherd
66   45880493        5                              Shepherd
67   45881113        5                    Labrador Retriever
68   45923730        5                                 Husky
69   45923725        5                             Dachshund
70   45923721        5                  Jack Russell Terrier
71   45923713        5                                Poodle
72   45954991        5                                 Husky
73   45923719        5                             Chihuahua
74   45923712        5   Australian Cattle Dog / Blue Heeler
75   45923711        5                            Rottweiler
76   45923724        5                  Jack Russell Terrier
77   45923733        5                               Terrier
78   45923732        5                             Retriever
79   45923728        5                             Retriever
80   45923729        5                             Retriever
81   45923727        5                  Jack Russell Terrier
82   45923726        5                             Chihuahua
83   45923731        5                      Wire Fox Terrier
84   45923723        5                    Miniature Pinscher
85   45923715        5                               Spaniel
86   44853480        5                    Labrador Retriever
87   45923133        4                                 Hound
88   45816520        4                             Chihuahua
89   45816519        4                         Saint Bernard
90   45816510        4                    Labrador Retriever
91   45816534        4                    Labrador Retriever
92   45816532        4                          Carolina Dog
93   45816525        4                    Labrador Retriever
94   45816524        4                          Basset Hound
95   45816517        4                                 Hound
96   45831371        4                                 Husky
97   45816512        4                    Labrador Retriever
98   45816508        4                    Labrador Retriever
99   45904452        4                      Pit Bull Terrier
100  45831451        4                 Catahoula Leopard Dog
101  46028357        4                    Labrador Retriever
102  45831316        4                 Catahoula Leopard Dog
103  37848260        4                    Labrador Retriever
104  37253070        4                    Labrador Retriever
105  44967275        4                             Dachshund
106  45964523        4                        Dutch Shepherd
107  45964157        4                   Miniature Schnauzer
108  45958381        4        American Staffordshire Terrier
109  45958355        4                   Miniature Schnauzer
110  45958304        4                            Rottweiler
111  45844990        4                        Great Pyrenees
112  45745151        4                    Labrador Retriever
113  45643803        4                             Dachshund
114  45589114        4                      Pit Bull Terrier
115  45546931        4        American Staffordshire Terrier
116  45230596        4   Australian Cattle Dog / Blue Heeler
117  44663527        4                         Presa Canario
118  44649688        4        American Staffordshire Terrier
119  44649686        4        American Staffordshire Terrier
120  45978371        4                      Pit Bull Terrier
121  45831383        4                                Beagle
122  45903656        4                              Shih Tzu
123  46041584        4                    Labrador Retriever
124  45923182        4                      American Bulldog
125  45923192        4                                 Hound
126  45958359        4                                 Boxer
127  45958363        4                      American Bulldog
128  46041165        4                              Shepherd
129  46041402        4                    Labrador Retriever
130  45726575        4                     Doberman Pinscher
131  45978368        4                      Pit Bull Terrier
132  45726574        4                     Doberman Pinscher
133  45802287        4                               Terrier
134  45838841        4                             Chihuahua
135  45897121        4                                Collie
136  45897122        4                 Catahoula Leopard Dog
137  45897176        4                    Labrador Retriever
138  45923174        4                         Border Collie
139  45923164        4                                 Hound
140  45782786        4                      American Bulldog
141  45782764        4                                 Hound
142  45754664        4                    Labrador Retriever
143  45754655        4                               Terrier
144  45664566        4                      American Bulldog
145  45664542        4                                 Hound
146  45664278        4                               Terrier
147  45497224        4                    Labrador Retriever
148  45469364        4                    Labrador Retriever
149  45960132        4                   German Shepherd Dog
150  45831331        4                                 Husky
151  45965584        4                             Chihuahua
152  45571226        4                             Chihuahua
153  45965792        4                             Chihuahua
154  45831398        4                                Beagle
155  45868688        4                                Collie
156  45958103        4                            Rottweiler
157  45908415        4                              Shar-Pei
158  44759435        4                      Golden Retriever
159  45844821        4                              Shepherd
160  45463453        4                   German Shepherd Dog
161  45977229        4                      Golden Retriever
162  45831368        4                    Labrador Retriever
163  44759438        4   Australian Cattle Dog / Blue Heeler
164  45781491        4                           Mixed Breed
165  45249846        4                    Labrador Retriever
166  44759434        4                    Labrador Retriever
167  24894894        4                                 Hound
168  46039420        4                         Border Collie
169  16657005        4                      Pit Bull Terrier
170  44759406        4                             Chihuahua
171  45830513        4                                 Spitz
172  45830510        4                                 Jindo
173  45642530        4                                 Jindo
174  24894870        4                                 Hound
175  45907353        4                    Labrador Retriever
176  44967336        4                    Labrador Retriever
177  45831430        4                    Labrador Retriever
178  41359772        4                   German Shepherd Dog
179  45117085        3                    Labrador Retriever
180  45117075        3                    Labrador Retriever
181  45079045        3                    Labrador Retriever
182  45964416        3              Black Labrador Retriever
183  46026615        3                               Terrier
184  45964450        3              Black Labrador Retriever
185  45079017        3                    Labrador Retriever
186  45965674        3                             Dachshund
187  45965673        3                             Dachshund
188  44662491        3                               Maltese
189  45051167        3              Black Labrador Retriever
190  45965467        3                    Australian Terrier
191  45965466        3                             Chihuahua
192  45964408        3              Black Labrador Retriever
193  45971387        3                     Yorkshire Terrier
194  45964143        3                              Papillon
195  46038557        3                             Retriever
196  45744743        3                    Labrador Retriever
197  45764757        3                             Chihuahua
198  45911676        3                        Border Terrier
199  45671661        3                    Labrador Retriever
200  45588395        3                   German Shepherd Dog
201  45657652        3                   German Shepherd Dog
202  45667646        3                    Labrador Retriever
203  45667631        3                    Labrador Retriever
204  45553633        3                    Labrador Retriever
205  45764737        3                     Yorkshire Terrier
206  45662979        3                       English Pointer
207  45414888        3                    Labrador Retriever
208  44562431        3                                 Boxer
209  42825396        3                Parson Russell Terrier
210  46016727        3                         Saint Bernard
211  46016726        3                        Boston Terrier
212  45414886        3                    Labrador Retriever
213  45083253        3                       Black Mouth Cur
214  44510615        3                                Saluki
215  46039522        3   Australian Cattle Dog / Blue Heeler
216  46039516        3                     Doberman Pinscher
217  45901417        3                    Labrador Retriever
218  46039523        3                   German Shepherd Dog
219  45929664        3                    Labrador Retriever
220  45758639        3              Black Labrador Retriever
221  45501584        3                    Labrador Retriever
222  45501566        3                    Labrador Retriever
223  45501542        3                    Labrador Retriever
224  45911675        3                                 Corgi
225  46019128        3                              Shih Tzu
226  45325825        3                             Greyhound
227  45930690        3                      American Bulldog
228  44077438        3                    Labrador Retriever
229  44267041        3             Yellow Labrador Retriever
230  45553658        3                    Labrador Retriever
231  45744151        3                    Labrador Retriever
232  45777269        3                    Labrador Retriever
233  44266927        3             Yellow Labrador Retriever
234  44077433        3                    Labrador Retriever
235  43576898        3                    Labrador Retriever
236  45781472        3                    Labrador Retriever
237  43576891        3                    Labrador Retriever
238  43401994        3                    Labrador Retriever
239  43379087        3                    Labrador Retriever
240  46038373        3                    Labrador Retriever
241  45850594        3                    Labrador Retriever
242  45984168        3                    Labrador Retriever
243  45983528        3                    Labrador Retriever
244  45976300        3                    Labrador Retriever
245  44372080        3                    Labrador Retriever
246  45772940        3                          Basset Hound
247  44372108        3                    Labrador Retriever
248  45773051        3                          Basset Hound
249  44944805        3                    Labrador Retriever
250  44944778        3                    Labrador Retriever
251  45964216        3              Black Labrador Retriever
252  45926575        3                 Flat-Coated Retriever
253  45926568        3                    Labrador Retriever
254  45926561        3                              Shih Tzu
255  45877931        3                              Shepherd
256  45877178        3                              Shepherd
257  45860148        3                    Labrador Retriever
258  45860053        3                      Golden Retriever
259  45773068        3                          Basset Hound
260  45772994        3                          Basset Hound
261  44441797        3                    Labrador Retriever
262  44915288        3                    Labrador Retriever
263  45772977        3                          Basset Hound
264  45772956        3                          Basset Hound
265  44915280        3                    Labrador Retriever
266  44770640        3                    Labrador Retriever
267  44770635        3                    Labrador Retriever
268  44551680        3                    Labrador Retriever
269  43529811        3                               Mastiff
270  44516671        3                    Labrador Retriever
271  44516642        3                    Labrador Retriever
272  44441937        3                    Labrador Retriever
273  45051161        3              Black Labrador Retriever
274  44551665        3                    Labrador Retriever
275  45911674        3                             Chihuahua
276  44978259        3              Treeing Walker Coonhound
277  46042372        3                    Labrador Retriever
278  46042569        3                    Labrador Retriever
279  46042587        3                    Labrador Retriever
280  46042618        3                    Labrador Retriever
281  46043099        3                    Labrador Retriever
282  46043149        3                    Labrador Retriever
283  46014033        3                                 Husky
284  44698204        3                                Poodle
285  46014085        3                         Cairn Terrier
286  46014084        3                                Poodle
287  42778494        3                  Jack Russell Terrier
288  43618547        3                      Alaskan Malamute
289  44095100        3           Belgian Shepherd / Malinois
290  44280068        3                             Dalmatian
291  46042334        3                    Labrador Retriever
292  46038360        3                    Labrador Retriever
293  46038340        3                    Labrador Retriever
294  46038304        3                    Labrador Retriever
295  46038279        3                    Labrador Retriever
296  46038273        3                    Labrador Retriever
297  40036107        3                      Pit Bull Terrier
298  46038201        3                    Labrador Retriever
299  44148011        3               Galgo Spanish Greyhound
300  45972178        3               Galgo Spanish Greyhound
301  45972205        3               Galgo Spanish Greyhound
302  46038191        3                    Labrador Retriever
303  45183644        3                                Saluki
304  45192185        3                                Borzoi
305  46030086        3                    Labrador Retriever
306  45907308        3                     Italian Greyhound
307  45907825        3                     Italian Greyhound
308  44375521        3                         Border Collie
309  44786575        3                                Poodle
310  45671695        3                    Labrador Retriever
311  45857750        3                              Papillon
312  45856888        3                            Pomeranian
313  45857543        3                               Maltese
314  45857542        3                         Japanese Chin
315  45857564        3                             Shiba Inu
316  45857729        3                                Poodle
317  45857728        3                                Poodle
318  45857751        3                        Cocker Spaniel
319  45026953        3                                 Jindo
320  45857766        3                                Poodle
321  45857767        3                                 Spitz
322  45857772        3                             Schnauzer
323  45857773        3                                Poodle
324  45857786        3                            Pomeranian
325  45591949        3  West Highland White Terrier / Westie

### 8. Fix the travels table so that the correct state is computed from the manual and the found fields. If manual is not missing, then it overrides what is stored in found.

In [27]:
import numpy as np


df2['correct state'] = np.where(df2['manual'].notnull(), df2['manual'], df2['found'])

# Print the result
print(df2[['manual','found','correct state']].head(60))

      manual        found correct state
0        NaN     Arkansas      Arkansas
1    Bahamas       Abacos       Bahamas
2   Maryland         Adam      Maryland
3        NaN      Adaptil       Adaptil
4        NaN  Afghanistan   Afghanistan
5        NaN  Afghanistan   Afghanistan
6       Ohio        Akron          Ohio
7       Ohio        Akron          Ohio
8        NaN      Alabama       Alabama
9        NaN      Alabama       Alabama
10       NaN      Alabama       Alabama
11       NaN      Alabama       Alabama
12       NaN      Alabama       Alabama
13       NaN      Alabama       Alabama
14       NaN      Alabama       Alabama
15       NaN      Alabama       Alabama
16       NaN      Alabama       Alabama
17       NaN      Alabama       Alabama
18       NaN      Alabama       Alabama
19       NaN      Alabama       Alabama
20       NaN      Alabama       Alabama
21       NaN      Alabama       Alabama
22       NaN      Alabama       Alabama
23       NaN      Alabama       Alabama
24       NaN      Alabama       Alabama
25       NaN      Alabama       Alabama
26       NaN      Alabama       Alabama
27       NaN      Alabama       Alabama
28       NaN      Alabama       Alabama
29       NaN      Alabama       Alabama
30       NaN      Alabama       Alabama
31       NaN      Alabama       Alabama
32       NaN      Alabama       Alabama
33       NaN      Alabama       Alabama
34       NaN      Alabama       Alabama
35       NaN      Alabama       Alabama
36       NaN      Alabama       Alabama
37       NaN      Alabama       Alabama
38       NaN      Alabama       Alabama
39       NaN      Alabama       Alabama
40       NaN      Alabama       Alabama
41       NaN      Alabama       Alabama
42       NaN      Alabama       Alabama
43       NaN      Alabama       Alabama
44       NaN      Alabama       Alabama
45       NaN      Alabama       Alabama
46       NaN      Alabama       Alabama
47       NaN      Alabama       Alabama
48       NaN      Alabama       Alabama
49       NaN      Alabama       Alabama
50       NaN      Alabama       Alabama
51       NaN      Alabama       Alabama
52       NaN      Alabama       Alabama
53       NaN      Alabama       Alabama
54       NaN      Alabama       Alabama
55       NaN      Alabama       Alabama
56       NaN      Alabama       Alabama
57       NaN      Alabama       Alabama
58       NaN      Alabama       Alabama
59       NaN      Alabama       Alabama

### 9. For each state, compute the ratio between the number of travels and the population.

In [14]:
df3 = pd.read_csv('dataset/NST-EST2021-POP.csv')

state_counts = df2['contact_state'].value_counts()

state_travel_df = pd.DataFrame({'contact_state': state_counts.index, 'travels': state_counts.values})

state_travel_population = pd.merge(state_travel_df, df3, on='contact_state')

state_travel_population['population'] = state_travel_population['population'].str.replace('.', '',regex=True).astype(float)
state_travel_population['travels'] = state_travel_population['travels'].astype(float)

state_travel_population['ratio10e6']= round((state_travel_population['travels']/state_travel_population['population'])*1000000)


state_travel_population.sort_values(by='ratio10e6', ascending=False)

   contact_state  travels                 state  population  ratio10e6
5             ME    361.0                 Maine   1362359.0      265.0
13            DC    112.0  District of Columbia    689545.0      162.0
0             VA   1025.0              Virginia   8631393.0      119.0
11            RI    130.0          Rhode Island   1097379.0      118.0
1             WA    634.0            Washington   7705281.0       82.0
26            VT     49.0               Vermont    643077.0       76.0
4             MD    379.0              Maryland   6177224.0       61.0
2             NJ    552.0            New Jersey   9288994.0       59.0
25            DE     57.0              Delaware    989948.0       58.0
19            NM     82.0            New Mexico   2117522.0       39.0
7             MN    190.0             Minnesota   5706494.0       33.0
27            NH     44.0         New Hampshire   1377529.0       32.0
17            CT     90.0           Connecticut   3605944.0       25.0
3             NY    490.0              New York  20201249.0       24.0
6             PA    316.0          Pennsylvania  13002700.0       24.0
23            UT     66.0                  Utah   3271616.0       20.0
16            CO    103.0              Colorado   5773714.0       18.0
8             NC    187.0        North Carolina  10439388.0       18.0
12            TN    112.0             Tennessee   6910840.0       16.0
15            MA    107.0         Massachusetts   7029917.0       15.0
34            WV     27.0         West Virginia   1793716.0       15.0
20            AL     75.0               Alabama   5024279.0       15.0
9             OH    177.0                  Ohio  11799448.0       15.0
18            WI     83.0             Wisconsin   5893718.0       14.0
21            AZ     70.0               Arizona   7151502.0       10.0
24            IN     65.0               Indiana   6785528.0       10.0
14            GA    109.0               Georgia  10711908.0       10.0
30            OR     32.0                Oregon   4237256.0        8.0
32            OK     31.0              Oklahoma   3959353.0        8.0
22            MI     67.0              Michigan  10077331.0        7.0
28            MO     42.0              Missouri   6154913.0        7.0
31            KY     31.0              Kentucky   4505836.0        7.0
35            IA     22.0                  Iowa   3190369.0        7.0
37            NV     20.0                Nevada   3104614.0        6.0
10            FL    133.0               Florida  21538187.0        6.0
36            SC     21.0        South Carolina   5118425.0        4.0
29            IL     37.0              Illinois  12812508.0        3.0
38            AR     10.0              Arkansas   3011524.0        3.0
39            MS      6.0           Mississippi   2961279.0        2.0
33            CA     28.0            California  39538223.0        1.0
40            LA      5.0             Louisiana   4657757.0        1.0
41            KS      3.0                Kansas   2937880.0        1.0
42            TX      2.0                 Texas  29145505.0        0.0

### 10. For each dog, compute the number of days from the posted day to the day of last access.

In [15]:
df[['id','name','stay_duration']].head(20)

          id         name  stay_duration
0   46042150       HARLEY             70
1   46042002       BIGGIE             49
2   46040898        Ziggy             87
3   46039877        Gypsy             62
4   46039306         Theo             93
5   46039304       Oliver             70
6   46039303    Macadamia             80
7   46039302       Dodger             46
8   46039301  Huckleberry             97
9   46038709        Fagin            112
10  46038708     Speckles             84
11  46038703       Cashew             75
12  46038700         Dash             78
13  46038243       Sydney            115
14  46038070        HENNA            117
15  46038064         RUBO            114
16  46038065         LEGO             82
17  46038067        MARIE            136
18  46038068        RINGO             94
19  46038060         TONY             91

### 11. Partition the dogs according to the number of weeks from the posted day to the day of last access.

In [16]:
df['weeks_stay_duration']=round(df['stay_duration']/7)


# the output has sorted from the max amount of weeks each dog has stayed

df[['id','name','stay_duration','weeks_stay_duration']].sort_values(by='weeks_stay_duration', ascending=False).head(20)

,id,name,stay_duration,weeks_stay_duration
13437,44569288,Joci,174,25.0
37480,45558784,Roxy,166,24.0
27661,44430986,Pitty Pablo-video,165,24.0
38236,45626995,Monty # 1754,165,24.0
25139,46029124,Britt,166,24.0
39252,31542985,Elvis,166,24.0
37913,46006930,Kiyoshi aka Baby Girl,168,24.0
30537,45949507,Polar,165,24.0
24659,43547728,Miss Piggy,158,23.0
35327,45955255,Hudson,159,23.0
15176,33661138,Darlin',159,23.0
40427,45827946,Millie,162,23.0
30629,45922074,RIVER,162,23.0
31303,45327667,Rocky,160,23.0
40179,45905708,Cy,160,23.0
18160,45211969,Nova&#39;s Pup Shelby,161,23.0
50663,45465400,Rebecca,159,23.0
16388,45917103,Camille *Adopt or Foster *,158,23.0
254,45866703,Hudsyn,164,23.0
21765,44572875,Charlotte,161,23.0

### 12. Find for duplicates in the dogs dataset. Two records are duplicates if they have (1) same breeds and sex, and (2) they share at least 90% of the words in the description field. Extra points if you find and implement a more refined for determining if two rows are duplicates.

In [20]:
counts = df.groupby(['breed_primary', 'sex']).size().reset_index(name='count')
counts.sort_values(by='count', ascending=False).head(40)

                           breed_primary     sex  count
299                     Pit Bull Terrier  Female   4105
300                     Pit Bull Terrier    Male   3785
236                   Labrador Retriever    Male   3739
235                   Labrador Retriever  Female   3459
111                            Chihuahua    Male   2002
110                            Chihuahua  Female   1764
263                          Mixed Breed    Male   1696
262                          Mixed Breed  Female   1544
373                              Terrier  Female   1372
374                              Terrier    Male   1269
211                                Hound    Male   1218
184                  German Shepherd Dog  Female   1083
210                                Hound  Female   1064
79                                 Boxer    Male   1054
185                  German Shepherd Dog    Male   1039
78                                 Boxer  Female    996
346                             Shepherd    Male    988
345                             Shepherd  Female    984
20        American Staffordshire Terrier  Female    932
21        American Staffordshire Terrier    Male    930
37                                Beagle    Male    830
36                                Beagle  Female    708
13                      American Bulldog    Male    655
25   Australian Cattle Dog / Blue Heeler    Male    510
12                      American Bulldog  Female    479
24   Australian Cattle Dog / Blue Heeler  Female    463
136                            Dachshund    Male    457
70                         Border Collie    Male    440
135                            Dachshund  Female    396
29                   Australian Shepherd    Male    386
69                         Border Collie  Female    377
225                 Jack Russell Terrier    Male    363
28                   Australian Shepherd  Female    310
324                           Rottweiler    Male    304
213                                Husky    Male    299
55              Black Labrador Retriever    Male    285
320                            Retriever    Male    278
224                 Jack Russell Terrier  Female    274
212                                Husky  Female    268
201                       Great Pyrenees    Male    261